### ISSUE TITLE
install.sh script cannot find amd64 binary

### ISSUE THREAD

**Issue by FrancoisPoinsot** [busser/tfautomv#55]
I tried running the install.sh script as the README states
```
curl -sSfL https://raw.githubusercontent.com/busser/tfautomv/main/install.sh | sh
```

on a amd64 machine.
The scripts tries to fetch "http_download https://github.com/busser/tfautomv/releases/download/v0.5.2/tfautomv_0.5.2_linux_amd64.tar.gz"

That link does not exist.
I guess it should be "tfautomv_0.5.2_linux_x86_64.tar.gz" instead.

**Comment by busser** [comment]
This is fixed as of now :) Thanks for reporting it!
