### ISSUE TITLE
Install tfautomv using asdf

### ISSUE THREAD

**Issue by amezioud** [busser/tfautomv#90]
It would be a good idea to provide tfautomv using the fabulous installer called asdf.

Doc aims to create a plugin : https://asdf-vm.com/plugins/create.html#create-a-plugin
Template below => https://github.com/asdf-vm/asdf-plugin-template

What do you think ?

**Comment by busser** [comment]
I'm absolutely for it. The more ways to install it the better!

I'll have a look. Thanks for sharing the docs, that will save me some time :)

**Comment by busser** [comment]
Done!

https://github.com/busser/tfautomv?tab=readme-ov-file#asdf

**Comment by amezioud** [comment]
Awesome thanks a lot !
